set -g mouse on

# プレフィックスを C-b から C-a に変更（screen風）
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# 分割を C-\ と - にする
bind "C-\\" split-window -h
bind - split-window -v

# プレフィックス無しでペイン移動（Alt+矢印）
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

# 設定リロードのショートカット
bind r source-file ~/.tmux.conf \; display "reloaded!"

# ホイールで上下矢印を送る挙動を止めて、代わりにcopy-modeに入る
bind -n WheelUpPane   if-shell -F -t = "#{alternate_on}" "send-keys -M" "copy-mode -e; send-keys -M"
bind -n WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "send-keys -M"
